uo-athletics:
  file: 
    - function
    - id_match_file
  identifier: 
    - regex
    - PH395_UP.*
  local_collection_name: 
    - string
    - PH395 UP
  local_collection_id: 
    - string
    - http://opaquenamespace.org/ns/localCollectionName/UniversityPhotosPaulHarveyIV

