Agent1_SortName: null
Agent2_SortName: null
Agent3_SortName: null
Agent_Display: null
GPS: null
Image_Description: null
Image_Filename: null
Image_IDNumber: null
Image_OriginalVendorID: null
Image_Rights: null
Image_Title: null
LocalCollection: null
SetAsThumb: null
SubjectDisplayCombined: null
Vendor_Name: null
WorkID: null
Work_AltTitle: null
Work_BuildingSiteName: null
Work_Classification: null
Work_Continent: null
Work_CultureDisplay: null
Work_DateDisplay: null
Work_DescriptionCombined: null
Work_InscriptionDisplay: null
Work_LocationCitySite: null
Work_LocationCombined: null
Work_LocationCountry: null
Work_LocationNotes: null
Work_MaterialDisplay: null
Work_MeasurementDisplay: null
Work_PrefTitle: null
Work_RelatedWorkCombined: null
Work_StateRegion: null
Work_StylePeriod1: null
Work_StylePeriod2: null
Work_StylePeriod3: null
Work_StylePeriod4: null
Work_StylePeriodDisplay: null
Work_TechniqueDisplay: null
Work_Worktype1: null
Work_Worktype2: null
Work_Worktype3: null
Work_Worktype4: null
Work_WorktypeDisplay: null
