dmrec:
  - regex: ^$
    which: all
file:
  - check_filenames_assets: ['file']
    which: all
subject:
  - validate_controlled_vocab: ['subject']
    which: all
creator:
  - validate_controlled_vocab: ['creator']

species: ~
# many more: # to do
# geonames add ending with /?