title: ~
subject: ~
description: ~
patron: ~
artist: ~
contributor: ~
date: ~
identifier: ~
resource_type: ~
style_or_period: ~
repository: ~
material: ~
full_size_download_allowed: ~
workType: 
  - regex: ^http:\/\/opaquenamespace\.org\/ns\/workType\/ICQSPU4k|http:\/\/vocab\.getty\.edu\/aat\/(300041273|300194222|300083023|300055099|300055023|300037321|300311670|300183938|300028731|300263751)$ # add other Getty options here
    which: all
item_locator: ~
rights_statement: ~
replaces_url: ~
institution: ~
measurements: ~
local_collection_name: ~
cultural_context: ~
rights_holder: ~
