title: ~
subject: ~
description: ~
patron: ~
artist: ~
contributor: ~
date: ~
identifier: ~
resource_type: ~
style_or_period: ~
repository: ~
material: ~
full_size_download_allowed: ~
workType: ~
item_locator: ~
rights_statement: ~
replaces_url: ~
institution: ~
measurements: ~
local_collection_name: ~
cultural_context: ~
rights_holder: ~
