# check against req'd cols for Bulkrax
id: ~
file:
  - regex
  - ^EX_COLL_123\d{1}_(recto|verso)\.png$
identifier:
  - regex
  - ^EX_COLL_123\S*$
title: ~
description: ~
local_collection_name: ~
local_collection_id: ~
date: ~
subject: ~
location: ~
resource_type: ~
format: ~
rights_statement: ~
license: ~
institution: ~
model: ~
visibility: ~
repository: ~
full_size_download_allowed: ~