date: ~
description: null
dmrec: null
file: # ^EX_COLL_123\d{1}_(recto|verso)\.png$
  - method
  - check_filenames_assets
format: null
full_size_download_allowed: null
identifier: 
  - regex
  - ^EX_COLL_123\S*$
institution: null
license: null
local_collection_id: null
local_collection_name: null
location: null
model: null
repository: null
resource_type: null
rights_statement: null
subject: null
title: null
visibility: null
