dmrec: ~
file: ~
title: ~
description:
identifier:
  - regex
  - ^PH395_UP\S*$ # any non-whitespace char too lax?
local_collection_name: 
  - regex
  - ^http:\/\/opaquenamespace.org\/ns\/localCollectionName\/UniversityPhotosPaulHarveyIV$
local_collection_id:
  - string
  - PH395 UP
photographer:
  - regex
  - ^http:\/\/opaquenamespace.org\/ns\/creator\/HarveyPaulWIV$
date: ~
subject: ~ # use regex? see bulkrax CSV doc for IRI constraints
location:
  - regex
  - ^https:\/\/sws.geonames.org/\S*$
resource_type:
  - regex
  - ^http:\/\/purl.org\/dc\/dcmitype\/Image$
format:
  - regex
  - ^https:\/\/w3id.org\/spar\/mediatype\/image\/tiff$
rights_statement: 
  - string # use regex instead? why am I using regex above but string here?
  - http://rightsstatements.org/vocab/InC/1.0/
license:
  - string
  - http://creativecommons.org/licenses/by-nd/4.0/
  # per !Bulkrax CSV Guidance Document URI should start http (not https)
rights_holder:
  - string
  - Harvey, Paul W., IV
# no 'parents' at this time for ingests - update later
institution:
  - string
  - http://id.loc.gov/authorities/names/n80126183
model:
  - string
  - Image
has_finding_aid:
  - string
  - https://scua.uoregon.edu/repositories/2/resources/9512
visibility:
  - string
  - open
repository:
  - string
  - http://id.loc.gov/authorities/names/no2003116678
full_size_download_allowed:
  - integer
  - 0