dmrec: ~
file:
  - method: check_filenames_assets
    args: ['file']
  - method: identifier_file_match
    args: ['.tif']
    # no which on method!
title: ~
description: ~
identifier:
  - regex: ^PH395_UP\S*$ # any non-whitespace char too lax?
    which: all
local_collection_name:
  - string: http://opaquenamespace.org/ns/localCollectionName/UniversityPhotosPaulHarveyIV
    which: all
local_collection_id:
  - string: PH395 UP
    which: all
photographer:
  - string: http://opaquenamespace.org/ns/creator/HarveyPaulWIV
    which: all
date:
  - regex: ^202[2-9]{1}-\d{2}-\d{2}$
    which: all
subject:
  - regex: (^http:\/\/id\.loc\.gov\/authorities\/subjects\/sh\d{1,15}$|^http:\/\/opaquenamespace\.org\/ns\/people\/\S*$)
    which: all
location: 
  - regex: ^https:\/\/sws.geonames.org/\S*$
    which: all
resource_type:
  - string: http://purl.org/dc/dcmitype/Image
    which: all
format:
  - string: https://w3id.org/spar/mediatype/image/tiff
    which: all
rights_statement:
  - string: http://rightsstatements.org/vocab/InC/1.0/
    which: all
license:
  - string: http://creativecommons.org/licenses/by-nc-nd/4.0/
    which: all
rights_holder:
  - string: Harvey, Paul W., IV
    which: all
parents:
  - string: uo-athletics
    which: all
institution: 
  - string: http://id.loc.gov/authorities/names/n80126183
    which: all
model:
  - string: Image
    which: all
has_finding_aid:
  - string: https://scua.uoregon.edu/repositories/2/resources/9512
    which: all
visibility:
  - string: open
    which: all
repository:
  - string: http://id.loc.gov/authorities/names/no2003116678
    which: all
full_size_download_allowed:
  - string: '0' # unclear why integers (and presumably
    # other numbers) must be quoted
    which: all
