# Tell od2validation.py which fields have the same validator (ex. photographer, aritst, and author all have the same validator as creator)
field_validators:
  creator:
    - creator
    - photographer
    - artist
    - author
    - contributor
    - applicant
    - arranger
    - cartographer
    - collector
    - composer
    - dedicatee
    - designer
    - donor
    - editor
    - illustrator
    - interviewee
    - interviewer
    - landscape architect
    - lyricist
    - owner
    - patron
    - print Maker
    - recipient
    - transcriber
    - translator
  subject:
    - subject
    - award
    - cultural context
    - ethnographic term
    - event
    - keyword
    - legal name
    - military branch
    - sports team
    # Note that spaces have to be the same between here and header column. Capitalization and using '/' is fine
    - style / edition
    - style / period
    - tribal classes
    - tribal terms

# Tell od2validation.py which vocabs correspond to each controlled vocab, so that they can all be checked
controlled_vocab_map:
  creator:
    - lcnaf
    - ulan
    - creator
    - people
    - wikidata
    - osuacademicunits

  subject:
    - lcsh
    - lcnaf
    - tgm
    - aat
    - subject
    - lcorgs
    - creator
    - people
    - itis
    # - ubio
    - osubuildings
    - wikidata
    - ulan
    - lcgenreforms
    - osuacademicunits
    # - bne
    # - homosaurus