# Tell od2validation.py which fields have the same validator (ex. photographer, aritst, and author all have the same validator as creator)
field_validators:
  creator:
    - creator
    - photographer
    - applicant
    - arranger
    - artist
    - author
    - cartographer
    - collector
    - composer
    - creator_display
    - contributor
    - arranger
    - dedicatee
    - designer
    - donor
    - editor
    - illustrator
    - interviewee
    - interviewer
    - landscape_architect
    - lyricist
    - owner
    - patron
    - print_maker
    - recipient
    - transcriber
    - translator
  subject:
    - subject
    - award
    - cultural_context
    - ethnographic_term
    - event
    - keyword
    - legal_name
    - military_branch
    - sports_team
    - state_or_edition
    - style_or_period
    - tribal_classes
    - tribal_terms

# Tell od2validation.py which vocabs correspond to each controlled vocab, so that they can all be checked
controlled_vocab_map:
  creator:
    - lcnaf
    - ulan
    - creator
    - people
    - wikidata
    - osuacademicunits

  subject:
    - lcsh
    - lcnaf
    - tgm
    - aat
    - subject
    - lcorgs
    - creator
    - people
    - itis
    # - ubio
    - osubuildings
    - wikidata
    - ulan
    - lcgenreforms
    - osuacademicunits
    - bne
    # - homosaurus