# Tell od2validation.py which fields have the same validator (ex. photographer, aritst, and author all have the same validator as creator)
field_validators:
  creator:
    - creator
    - photographer
    - applicant
    - arranger
    - artist
    - author
    - cartographer
    - collector
    - composer
    - contributor
    - dedicatee
    - designer
    - donor
    - editor
    - illustrator
    - interviewee
    - interviewer
    - landscape_architect
    - lyricist
    - owner
    - patron
    - print_maker
    - recipient
    - transcriber
    - translator
  subject:
    - subject
    - military_branch
  ethnographic_term:
    - ethnographic_term
  cultural_context:
    - cultural_context

# Tell od2validation.py which vocabs correspond to each controlled vocab, so that they can all be checked
controlled_vocab_map:
  creator:
    - lcnaf
    - ulan
    - creator
    - people
    - wikidata
    - osuacademicunits
    - publisher
  subject:
    - lcsh
    - lcnaf
    - tgm
    - aat
    - subject
    - lcorgs
    - creator
    - people
    - itis
    # - ubio
    - osubuildings
    - wikidata
    - ulan
    - lcgenreforms
    - osuacademicunits
    - bne
    - homosaurus
  ethnographic_term:
    - afs_ethn
  cultural_context:
    - aat
    - lcsh
    - lcnaf
    - culture