files: L:/DigitalProjects/Metadata/uo_athletics/Work/processing/20240608_NCAA_4_TF/files
metadata: C:/Users/briesenb/OneDrive - University Of Oregon/bmr_metadata_general_asstd/OD2_working_files/uo_athletics/20240608_NCAA_4_TF.csv
