# Global is a special reserved keyword for checks that should run on every single row and column
global:
  - row_limit_from_assets: true

file:
  - check_filenames_assets: ['file']
    which: all
subject:
  - validate_controlled_vocab: ['subject']
    which: all
creator:
  - validate_controlled_vocab: ['creator']
    which: all
workType:
  - validate_controlled_vocab: ['workType']
    which: all
