file:
  - check_filenames_assets: ['file']
    which: all
subject:
  - validate_controlled_vocab: ['subject']
    which: all
creator:
  - validate_controlled_vocab: ['creator']
    which: all
workType:
  - validate_controlled_vocab: ['workType']
    which: all
